"use strict";
var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k;
Object.defineProperty(exports, "__esModule", { value: true });
exports.DAYLY_REWARDS = exports.refreshTokenNameInCookies = void 0;
var boost_enum_1 = require("../enums/boost.enum");
exports.refreshTokenNameInCookies = 'refresh_token';
exports.DAYLY_REWARDS = [
    (_a = {},
        _a[boost_enum_1.BoostsNames.boosts_moveboss] = 1,
        _a[boost_enum_1.BoostsNames.boosts_powerwisps] = 1,
        _a[boost_enum_1.BoostsNames.boosts_remove] = 1,
        _a[boost_enum_1.BoostsNames.boosts_repaint] = 1,
        _a[boost_enum_1.BoostsNames.boosts_upgrade] = 1,
        _a),
    (_b = {},
        _b[boost_enum_1.BoostsNames.boosts_moveboss] = 2,
        _b[boost_enum_1.BoostsNames.boosts_powerwisps] = 2,
        _b[boost_enum_1.BoostsNames.boosts_remove] = 2,
        _b[boost_enum_1.BoostsNames.boosts_repaint] = 2,
        _b[boost_enum_1.BoostsNames.boosts_upgrade] = 2,
        _b),
    (_c = {},
        _c[boost_enum_1.BoostsNames.boosts_moveboss] = 3,
        _c[boost_enum_1.BoostsNames.boosts_powerwisps] = 3,
        _c[boost_enum_1.BoostsNames.boosts_remove] = 3,
        _c[boost_enum_1.BoostsNames.boosts_repaint] = 3,
        _c[boost_enum_1.BoostsNames.boosts_upgrade] = 3,
        _c),
    (_d = {},
        _d[boost_enum_1.BoostsNames.boosts_moveboss] = 4,
        _d[boost_enum_1.BoostsNames.boosts_powerwisps] = 4,
        _d[boost_enum_1.BoostsNames.boosts_remove] = 4,
        _d[boost_enum_1.BoostsNames.boosts_repaint] = 4,
        _d[boost_enum_1.BoostsNames.boosts_upgrade] = 4,
        _d),
    (_e = {},
        _e[boost_enum_1.BoostsNames.boosts_moveboss] = 5,
        _e[boost_enum_1.BoostsNames.boosts_powerwisps] = 5,
        _e[boost_enum_1.BoostsNames.boosts_remove] = 5,
        _e[boost_enum_1.BoostsNames.boosts_repaint] = 5,
        _e[boost_enum_1.BoostsNames.boosts_upgrade] = 5,
        _e),
    (_f = {},
        _f[boost_enum_1.BoostsNames.boosts_moveboss] = 6,
        _f[boost_enum_1.BoostsNames.boosts_powerwisps] = 6,
        _f[boost_enum_1.BoostsNames.boosts_remove] = 6,
        _f[boost_enum_1.BoostsNames.boosts_repaint] = 6,
        _f[boost_enum_1.BoostsNames.boosts_upgrade] = 6,
        _f),
    (_g = {},
        _g[boost_enum_1.BoostsNames.boosts_moveboss] = 7,
        _g[boost_enum_1.BoostsNames.boosts_powerwisps] = 7,
        _g[boost_enum_1.BoostsNames.boosts_remove] = 7,
        _g[boost_enum_1.BoostsNames.boosts_repaint] = 7,
        _g[boost_enum_1.BoostsNames.boosts_upgrade] = 7,
        _g),
    (_h = {},
        _h[boost_enum_1.BoostsNames.boosts_moveboss] = 8,
        _h[boost_enum_1.BoostsNames.boosts_powerwisps] = 8,
        _h[boost_enum_1.BoostsNames.boosts_remove] = 8,
        _h[boost_enum_1.BoostsNames.boosts_repaint] = 8,
        _h[boost_enum_1.BoostsNames.boosts_upgrade] = 8,
        _h),
    (_j = {},
        _j[boost_enum_1.BoostsNames.boosts_moveboss] = 9,
        _j[boost_enum_1.BoostsNames.boosts_powerwisps] = 9,
        _j[boost_enum_1.BoostsNames.boosts_remove] = 9,
        _j[boost_enum_1.BoostsNames.boosts_repaint] = 9,
        _j[boost_enum_1.BoostsNames.boosts_upgrade] = 9,
        _j),
    (_k = {},
        _k[boost_enum_1.BoostsNames.boosts_moveboss] = 10,
        _k[boost_enum_1.BoostsNames.boosts_powerwisps] = 10,
        _k[boost_enum_1.BoostsNames.boosts_remove] = 10,
        _k[boost_enum_1.BoostsNames.boosts_repaint] = 10,
        _k[boost_enum_1.BoostsNames.boosts_upgrade] = 10,
        _k),
];
